### ISSUE TITLE
make file does not handle spaces in path

### ISSUE THREAD

**Issue by aradford123** [davidmcgrew/joy#9]
One of my parent directories had a space in it.  This cause the make to fail.

gcc -Wall -Wno-deprecated-declarations -g -O3   -DDARWIN=1 -DVERSION=\"1.2\" -o /Users/aradford1/Documents/work/interest/PROJECTS/UNSW - research/work/joy/bin/pcap2flow -I ./include -I /opt/local/include pcap2flow.c p2f.c config.c osdetect.c anon.c pkt_proc.c nfv9.c tls.c classify.c radix_trie.c hdr_dsc.c procwatch.c addr_attr.c addr.c wht.c http.c str_match.c acsm.c dns.c example.c -L /usr/lib -lpcap     -lm       -lcrypto  -lz  
clang: error: -E or -x required when input is from standard input
clang: error: no such file or directory: 'research/work/joy/bin/pcap2flow'
make[1]: *** [pcap2flow] Error 1
make: *** [pcap2flow] Error 2

**Comment by fliphil** [comment]
This is not due to an error with the Joy library. The bash shell has a hard time interpreting directories with spaces in them, because spaces are often used as parsing delimiters for the shell language.

To fix this you either need to rename the directory to not have any spaces, or surround the directory path with quotes when you enter that command.

**Comment by aradford123** [comment]
I understand, however, it is the joy makefile and config script that is generating the above?  It needs to have quotes put into it.

**Comment by bhudson33** [comment]
This will be fixed in the next push. Thanks for the comments!

Cheers,
Bill.

On Oct 9, 2016, at 7:51 PM, aradford123 <notifications@github.com<mailto:notifications@github.com>> wrote:


I understand, however, it is the joy makefile and config script that is generating the above? It needs to have quotes put into it.
